// app/layout.js
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { NextAuthProvider } from "./providers";

export const metadata = {
  title: {
    template: "%s | Blog App",
    default: "Blog App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className="antialiased min-h-screen flex flex-col px-8">
        <NextAuthProvider>
          {children}
          <Toaster position="bottom-right" />
        </NextAuthProvider>
      </body>
    </html>
  );
}
